Repository Your-Planet/back-end, pull requests merged in 2025-05, with the labels that each got.

#177 [YP-736] fix: 파일 메타데이터 관련 프로필 이미지 생성/조회, 프로젝트 참조자료 등록/조회 수정
  yp-core/src/main/java/kr/co/yourplanet/core/entity/project/Project.java
  yp-core/src/main/java/kr/co/yourplanet/core/entity/project/ProjectReferenceFile.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/file/adapter/StorageAdapter.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/file/repository/FileMetadataRepository.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/file/service/FileQueryService.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/file/service/FileUrlService.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/project/controller/ProjectController.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/project/repository/ProjectReferenceFileRepository.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/project/service/impl/ProjectServiceImpl.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/studio/dao/StudioBasicDao.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/studio/repository/StudioRepositoryImpl.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/studio/service/ProfileService.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/studio/service/impl/CreatorServiceImpl.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/studio/service/impl/ProfileServiceImpl.java
  yp-online/src/main/java/kr/co/yourplanet/online/infra/aws/S3StorageAdapter.java
  yp-online/src/main/java/kr/co/yourplanet/online/properties/FileProperties.java
  yp-online/src/main/resources/application-dev.yaml
  yp-online/src/main/resources/application-local.yaml
  yp-online/src/main/resources/db/migration/V1.11__delete_project_reference_file_table.sql
Labels: bug, D-1

#175 [YP-735] 프로젝트 정산 관련 기반 구현 및 정산 목록 조회 API, 정산 대기건 조회 API 구현
  yp-core/build.gradle
  yp-core/src/main/java/kr/co/yourplanet/core/config/QueryDslConfig.java
  yp-core/src/main/java/kr/co/yourplanet/core/entity/file/FileMetadata.java
  yp-core/src/main/java/kr/co/yourplanet/core/entity/payment/PaymentHistory.java
  yp-core/src/main/java/kr/co/yourplanet/core/entity/payment/PaymentType.java
  yp-core/src/main/java/kr/co/yourplanet/core/entity/project/ProjectContract.java
  yp-core/src/main/java/kr/co/yourplanet/core/entity/settlement/ProjectSettlement.java
  yp-core/src/main/java/kr/co/yourplanet/core/entity/settlement/SettlementPaymentStatus.java
  yp-core/src/main/java/kr/co/yourplanet/core/entity/settlement/SettlementStatus.java
  yp-core/src/main/java/kr/co/yourplanet/core/enums/FilePathKey.java
  yp-core/src/main/java/kr/co/yourplanet/core/enums/FileType.java
  yp-core/src/main/java/kr/co/yourplanet/core/model/PageInfo.java
  yp-core/src/main/java/kr/co/yourplanet/core/model/PagedResponse.java
  yp-core/src/main/java/kr/co/yourplanet/core/util/FeeCalculator.java
  yp-online/build.gradle
  yp-online/src/main/java/kr/co/yourplanet/online/business/file/repository/FileMetadataRepository.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/file/service/FileQueryService.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/file/service/FileService.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/file/service/FileValidationService.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/controller/PaymentController.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/controller/dto/request/PaymentApproveForm.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/service/PaymentHistoryService.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/service/PaymentService.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/service/dto/PaymentResponse.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/service/impl/PaymentHistoryServiceImpl.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/service/impl/PaymentServiceImpl.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/service/processor/PaymentProcessor.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/service/processor/PaymentProcessorFactory.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/service/processor/ProjectPaymentProcessor.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/project/controller/ProjectController.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/project/dto/response/ContractInfo.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/project/service/ContractDraftService.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/project/service/ProjectValidationService.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/project/service/impl/ProjectServiceImpl.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/settlement/controller/SettlementController.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/settlement/dto/ProjectBasicInfo.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/settlement/dto/ProjectSettlementSummariesInfo.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/settlement/dto/ProjectSettlementSummaryInfo.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/settlement/dto/ProjectSpecInfo.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/settlement/dto/SettlementInfo.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/settlement/dto/SponsorInfo.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/settlement/repository/ProjectSettlementJpaRepository.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/settlement/repository/ProjectSettlementRepository.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/settlement/repository/ProjectSettlementRepositoryCustom.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/settlement/repository/impl/ProjectSettlementRepositoryCustomImpl.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/settlement/service/ProjectSettlementQueryService.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/settlement/service/ProjectSettlementService.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/user/service/MemberValidationService.java
  yp-online/src/main/java/kr/co/yourplanet/online/common/exception/BadRequestException.java
  yp-online/src/main/java/kr/co/yourplanet/online/common/exception/InternalServerErrorException.java
  yp-online/src/main/java/kr/co/yourplanet/online/config/WebSecurityConfig.java
  yp-online/src/main/java/kr/co/yourplanet/online/jwt/JwtPrincipal.java
  yp-online/src/main/java/kr/co/yourplanet/online/jwt/JwtTokenProvider.java
  yp-online/src/main/resources/application.yaml
  yp-online/src/main/resources/db/migration/V1.12__modify_file_metadata_target_cloumn_name.sql
  yp-online/src/main/resources/db/migration/V1.13__modify_payment_history_target.sql
  yp-online/src/main/resources/db/migration/V1.14__create_table_project_settlement.sql
  yp-online/src/main/resources/db/migration/V1.15__modify_column_name_deadline.sql
  yp-online/src/test/java/kr/co/yourplanet/online/business/settlement/controller/SettlementControllerTest.java
  yp-online/src/test/resources/db/setup.sql
Labels: D-0, feat

#176 [YP-842] feat : 프로젝트 상태 추가 (수락, 진행중, 정산완료)
  yp-core/src/main/java/kr/co/yourplanet/core/entity/project/Project.java
  yp-core/src/main/java/kr/co/yourplanet/core/enums/ProjectStatus.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/service/processor/ProjectPaymentProcessor.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/project/controller/ProjectController.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/project/service/ContractValidationService.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/project/service/ProjectValidationService.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/project/service/impl/ProjectServiceImpl.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/settlement/service/ProjectSettlementService.java
  yp-online/src/test/resources/db/setup.sql
Labels: D-0
