Repository Your-Planet/back-end, pull requests merged in 2025-01, with the labels that each got.

#142 [YP-624] env: secret 값을 설정파일에서 분리
  .gitignore
  yp-online/src/main/resources/application-dev.yaml
  yp-online/src/main/resources/application-local.yaml
  yp-online/src/main/resources/application.yaml
  yp-online/src/main/resources/data.sql
  yp-online/src/main/resources/logback-spring.xml
Labels: D-3, env

#141 [YP-626] env: 매일 자정 dn 라벨 자동 갱신 워크플로우 생성
  .github/workflows/dnrule.yml
Labels: D-3, env

#140 [YP-625] env: PR template 등록
  .github/PULL_REQUEST_TEMPLATE.md
Labels: D-2, env

#146 [YP-640] refactor : Project 리스트 조회 API URL 수정
  yp-online/src/main/java/kr/co/yourplanet/online/business/project/controller/ProjectController.java
Labels: D-2

#144 [YP-623] env: CI 워크플로우 작성
  .github/workflows/ci.yml
  .gitignore
  yp-batch/src/main/java/kr/co/yourplanet/batch/YpBatchApplication.java
  yp-batch/src/main/resources/application-dev.yaml
  yp-batch/src/main/resources/application-local.yaml
  yp-batch/src/main/resources/application.yaml
Labels: D-0, env

#148 [YP-603] doc: Swagger 의존성 변경 (Spring fox -> Spring doc)
  yp-online/build.gradle
  yp-online/src/main/java/kr/co/yourplanet/online/business/instagram/controller/InstagramController.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/project/controller/ProjectController.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/studio/controller/CreatorController.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/studio/controller/StudioController.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/user/controller/AuthController.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/user/controller/MemberController.java
  yp-online/src/main/java/kr/co/yourplanet/online/config/SwaggerConfig.java
  yp-online/src/main/resources/application-local.yaml
  yp-online/src/main/resources/application.yaml
Labels: documentation, D-0, env

#145 [YP-591] refactor : 파일 유효성 검사 공통화
  yp-core/src/main/java/kr/co/yourplanet/core/enums/FileType.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/studio/service/impl/ProfileServiceImpl.java
  yp-online/src/main/java/kr/co/yourplanet/online/common/util/FileManageUtil.java
Labels: enhancement, D-4
