Repository Your-Planet/back-end, pull requests merged in 2025-02, with the labels that each got.

#147 [YP-530] feat: 결제 관련 API 구현
  build.gradle
  yp-batch/build.gradle
  yp-core/src/main/java/kr/co/yourplanet/core/entity/payment/PaymentHistory.java
  yp-core/src/main/java/kr/co/yourplanet/core/entity/payment/PaymentProvider.java
  yp-core/src/main/java/kr/co/yourplanet/core/entity/payment/PaymentStatus.java
  yp-core/src/main/java/kr/co/yourplanet/core/enums/StatusCode.java
  yp-online/build.gradle
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/controller/PaymentController.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/controller/dto/request/PaymentApproveForm.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/controller/dto/request/PaymentRequestForm.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/domain/IdempotencyKeyGenerator.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/domain/exception/PaymentFailureException.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/domain/exception/PaymentRequestNotFoundException.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/domain/exception/PaymentRequestNotMatchException.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/repository/PaymentHistoryRepository.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/repository/PaymentRequestRepository.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/service/PaymentClient.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/service/PaymentHistoryService.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/service/PaymentRequestService.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/service/PaymentService.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/service/dto/PaymentRequest.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/service/dto/PaymentResponse.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/service/impl/PaymentHistoryServiceImpl.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/service/impl/PaymentRequestServiceImpl.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/payment/service/impl/PaymentServiceImpl.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/project/service/ProjectValidationService.java
  yp-online/src/main/java/kr/co/yourplanet/online/common/ResponseForm.java
  yp-online/src/main/java/kr/co/yourplanet/online/common/exception/BusinessException.java
  yp-online/src/main/java/kr/co/yourplanet/online/common/exception/GlobalExceptionHandler.java
  yp-online/src/main/java/kr/co/yourplanet/online/config/RedisConfig.java
  yp-online/src/main/java/kr/co/yourplanet/online/config/RestClientConfig.java
  yp-online/src/main/java/kr/co/yourplanet/online/infra/redis/RedisPaymentRequestRepository.java
  yp-online/src/main/java/kr/co/yourplanet/online/infra/redis/RedisRepository.java
  yp-online/src/main/java/kr/co/yourplanet/online/infra/web/payment/TossPaymentApiClient.java
  yp-online/src/main/java/kr/co/yourplanet/online/infra/web/payment/TossPaymentErrorCode.java
  yp-online/src/main/resources/application-dev.yaml
  yp-online/src/main/resources/application-local.yaml
  yp-online/src/main/resources/db/migration/V1.1__create_table_payment_history.sql
  yp-online/src/main/resources/test-secret.properties
Labels: enhancement, D-0

#151 [YP-668] feat: S3 도입 및 presigned url 요청 API 구현
  .github/workflows/ci.yml
  yp-core/src/main/java/kr/co/yourplanet/core/entity/FileMetadataKeys.java
  yp-core/src/main/java/kr/co/yourplanet/core/enums/FileType.java
  yp-core/src/main/java/kr/co/yourplanet/core/enums/StatusCode.java
  yp-online/build.gradle
  yp-online/src/main/java/kr/co/yourplanet/online/business/file/adapter/StorageAdapter.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/file/controller/FileController.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/file/dto/PresignedUrlsForm.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/file/dto/PresignedUrlsResponse.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/file/service/FileUploadService.java
  yp-online/src/main/java/kr/co/yourplanet/online/common/util/FileManageUtil.java
  yp-online/src/main/java/kr/co/yourplanet/online/config/AwsS3Config.java
  yp-online/src/main/java/kr/co/yourplanet/online/config/WebSecurityConfig.java
  yp-online/src/main/java/kr/co/yourplanet/online/infra/aws/S3StorageAdapter.java
  yp-online/src/main/java/kr/co/yourplanet/online/properties/FileProperties.java
  yp-online/src/main/resources/application-dev.yaml
  yp-online/src/main/resources/application-local.yaml
Labels: D-0, feat

#150 [YP-304] 멤버 도메인, 회원가입 리팩터링 및 회원 정보 수정 API 구현
  .gitignore
  Dockerfile
  yp-batch/src/main/java/kr/co/yourplanet/batch/job/InstagramBatchProcessor.java
  yp-core/src/main/java/kr/co/yourplanet/core/entity/member/AccountInfo.java
  yp-core/src/main/java/kr/co/yourplanet/core/entity/member/AgreementInfo.java
  yp-core/src/main/java/kr/co/yourplanet/core/entity/member/BusinessInfo.java
  yp-core/src/main/java/kr/co/yourplanet/core/entity/member/InstagramInfo.java
  yp-core/src/main/java/kr/co/yourplanet/core/entity/member/Member.java
  yp-core/src/main/java/kr/co/yourplanet/core/entity/member/MemberBasicInfo.java
  yp-core/src/main/java/kr/co/yourplanet/core/entity/member/SettlementInfo.java
  yp-core/src/main/java/kr/co/yourplanet/core/enums/BusinessType.java
  yp-core/src/main/java/kr/co/yourplanet/core/util/LocalDateStringConverter.java
  yp-online/build.gradle
  yp-online/src/main/java/kr/co/yourplanet/online/business/studio/service/impl/ProfileServiceImpl.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/user/controller/AuthController.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/user/controller/MemberController.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/user/dto/BaseJoinForm.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/user/dto/BusinessForm.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/user/dto/CreatorJoinForm.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/user/dto/InstagramForm.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/user/dto/JoinForm.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/user/dto/LoginForm.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/user/dto/MemberDetail.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/user/dto/MemberJoinForm.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/user/dto/TermsForm.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/user/dto/TermsInfo.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/user/dto/update/BaseUpdateForm.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/user/dto/update/CreatorUpdateForm.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/user/dto/update/MemberUpdateForm.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/user/dto/update/SettlementForm.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/user/repository/MemberRepository.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/user/service/MemberCreateService.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/user/service/MemberJoinService.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/user/service/MemberQueryService.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/user/service/MemberService.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/user/service/MemberUpdateService.java
  yp-online/src/main/java/kr/co/yourplanet/online/business/user/service/MemberValidationService.java
  yp-online/src/main/java/kr/co/yourplanet/online/common/exception/BadRequestException.java
  yp-online/src/main/java/kr/co/yourplanet/online/common/exception/GlobalExceptionHandler.java
  yp-online/src/main/resources/application-dev.yaml
  yp-online/src/main/resources/application-local.yaml
  yp-online/src/main/resources/application.yaml
  yp-online/src/main/resources/data.sql
  yp-online/src/main/resources/db/migration/V1.1__add_member_columns.sql
  yp-online/src/main/resources/db/migration/V1.1__create_table_payment_history.sql
  yp-online/src/main/resources/db/migration/V1.2__create_table_payment_history.sql
  yp-online/src/main/resources/db/migration/V1__init.sql
Labels: enhancement, D-0, feat

#157 [YP-707] fix : Member 엔티티 구조 변경에 따른 작가검색 쿼리 수정
  yp-online/src/main/java/kr/co/yourplanet/online/business/studio/repository/StudioRepositoryImpl.java
Labels: D-2
